(executable
 (name main)
 (preprocess
  (pps ppx_let))
 (libraries
  spectec
  spectec.grammar
  spectec.parsegen
  spectec.targets.impty
  spectec.lang
  bignum.bigint
  core
  core_unix.command_unix))

(rule
 (target impty.actual)
 (deps
  (source_tree ../../testdata/interp/impty/base)
  main.exe)
 (action
  (with-stdout-to
   %{target}
   (with-stderr-to
    impty.err
    (run
     ./main.exe
     -s
     %{dep:../../specs/impty/base/spec.spectec}
     -d
     ../../testdata/interp/impty/base)))))

(rule
 (alias runtest)
 (action
  (diff impty.expected impty.actual)))
