(ocamllex
 (modules lexer))

(menhir
 (flags -v --fixed-exception)
 (modules parse))

(library
 (name targets_miniml)
 (public_name spectec.targets.miniml)
 (modules
  (:standard \ register))
 (libraries
  spectec
  spectec.cli
  spectec.common
  spectec.grammar
  spectec.lang
  spectec.lang.il
  spectec.interp.builtins
  core
  str)
 (preprocess
  (pps ppx_let)))

(library
 (name register_miniml)
 (public_name spectec.targets.miniml.plugin)
 (modules register)
 (libraries spectec.cli spectec.targets.miniml))

(plugin
 (name miniml)
 (package spectec)
 (libraries spectec.targets.miniml.plugin)
 (site
  (spectec target_plugins)))
