(ocamllex
 (modules lexer))

(menhir
 (flags -v --fixed-exception)
 (modules parse))

(library
 (name targets_miniml)
 (public_name spectec-target-miniml.target)
 (modules
  (:standard \ register))
 (libraries
  spectec
  spectec.cli
  spectec.common
  spectec.grammar
  spectec.lang
  spectec.lang.il
  spectec.interp.builtins
  core
  dune-site
  str)
 (preprocess
  (pps ppx_let)))

(generate_sites_module
 (module miniml_sites)
 (sites spectec-target-miniml))

(library
 (name register_miniml)
 (public_name spectec-target-miniml.plugin)
 (modules register)
 (libraries spectec.cli spectec-target-miniml.target))

(plugin
 (name miniml)
 (package spectec-target-miniml)
 (libraries spectec-target-miniml.plugin)
 (site
  (spectec target_plugins)))
